vocabulary = [
# ================ SEITE 4/5 ================ #

# -------- A -------- #
["a, ab", "von, von ... her"],
["abdere", "-didi, -ditum", "verbergen"],
["abesse", "-sum, afui", "entfernt sein"],
["accedere", "-cessi, -cessum", "herankommen", [
    ["accedit", "es kommt hinzu"]]],
["accidere", "accidi", "geschehen"],
["accipere", "-io, -cepi, -ceptum", "empfangen"],
["acies", "-ei f", "1. Schlachtordnung\n2. Heeresgruppe(in der Schlacht)"],
["acriter", "heftig"],
["ad", "1. zu\n2. in der Nähe von"],
["adducere", "-duxi, -ductum", "1. hinführen\n2. veranlassen"],
["adesse", "-sum, -fui", "da sein"],
["adire", "-eo -ii, -itum", "hingehen"],
["aditus", "-us m", "Zugang"],
["administrare", "-vi, -tum", "durchführen"],
["adoriri", "-ortus sum {dep.}", "angreifen"],
["adulescens", "-entis m", "1. jung\n2. junger Mann"],
["adventus", "-us m", "Ankunft"],
["aedificium", "-ii n", "Gehöft {Bauernhof, Gebäude}"],
["aequus", "(-a, -um)", "1. eben\n2. gleich\n3. günstig\n4. gerecht"],
["aestus", "-us m", "Flut"],
["afferre", "affero, attuli, allatum", "bringen"],
["ager", "-gri m", "Feld"],
["agere", "egi, actum", "1. tun\n2. verhandeln"],
["agger", "-eris m", "Erdwall"],
["agmen", "-minis n", "Heer (auf dem Marsch)"],

["aliquis", "(aliquid) (subst.)", "irgendjemand, -einer, (-etwas)"],
["aliqui", "(-quae, -quod) (adj.)", "irgendein, (-eine)", "{'aliqui nomo'}"], # TODO
["alius", "(-a, -ud)", "ein anderer", [
    ["alii ... alii", "die einen ... die anderen"]]],
["alter", "-era -erum", "1. der andere\n2. der zweite", [
    ["alter ... alter", "der eine ... der andere"]]],
["altitudo", "-dinis f", "1. Höhe\n2. Tiefe"],
["altus", "(-a, -um)", "1. hoch\n2. tief"],
["amicitia", "-ae f", "Freundschaft"],
["amicus", "-i m", "Freund"],
["amittere", "-misi, -missum", "verlieren"],
["amplius", "mehr"],
["angstus", "(-a, -um)", "eng"],
["animadvertere", "-verti, -versum", "bemerken"],
["animus", "-i m", "Inneres: Geist, Herz, Mut"],
["annus", "-i m", "Jahr"],
["ante", "1. vor\n2. vorher"],
["apertus", "(-a, -um)", "1. offen\n2. ungeschützt"],
["appellare", "-vi, -tum", "1. ansprechen\n2. nennen"],
["appropinquare", "-vi", "sich nähern"],
["apud", "bei"],
["arbitrari", "-tus sum {dep.}", "meinen"],
["arcessere", "-sivi, -situm", "herbeirufen"],
["arma", "-orum n {pl.}", "Waffen"],
["armare", "-vi, -tum", "bewaffnen"],
["ascendere", "-scendi, -scensum", "hinaufsteigen"],
["at", "aber"],
["atque, ac", "1. und\n2. wie, als (z.B. alius atque)"],

["attingere", "attigi, attactum", "berühren"],
["attribuere", "-ui -utum", "zuteilen"],
["auctoritas", "-atis f", "Ansehen"],
["audere", "ausus sum", "wagen"],
["audire", "-vi -tum", "hören"],
["augere", "auxi, auctum", "vergrößern"],
["aut", "oder", [
    ["aut ... aut", "entweder ... oder"]]],
["autem", "aber"],
["auxilium", "-ii n", "Sg: Hilfe\nPl: Hilfstruppen"],
# -------- B -------- #
["barbarus", "(-a, -um)", "1. unkultiviert\n2. der Fremde(= Nichtrömer)"],
["bellum", "-i n", "Krieg"],
["beneficium", "-ii n", "1. Wohltat\n2. das Verdienst"],
["bonus", "(-a, -um)", "gut", "Komp. melior\nSuperl. optimus"],
# -------- C -------- #
["caedes", "-is f", "Mord/Morden"],
["calamitas", "-atis f", "Niederlage"],
["capere", "-io, cepi, captum", "1. fassen\n2. fangen\n3. einnehmen"],
["captivus", "-i m", "Gefangener"],
["castellum", "-i n", "Befestigung"],
["castra", "-orum n", "Lager"],
["casus", "-us m", "Ereignis, Situation", [
    ["casu", "durch Zufall"]]],
["caus[a]", "-ae f", "1. Sache\n2. Ursache, Grund"],
["caus[ā]", "wegen"],
["cedere", "cessi, cessum", "zurückweichen"],
["celeritas", "-atis f", "Schnelligkeit"],

["celeriter", "schnell"],
["centum", "hundert"],
["centurio", "-onis m", "Hauptmann, Centurio"],
["certus", "(-a, -um)", "bestimmt", [
    ["certiorem facere", "benachrichtigen"]]],
["circiter", "ungefähr"],
["circumvenire", "-veni, -ventum", "umzingeln"],
["civitas", "-atis f", "Staat, Volk"],
["clamor", "-oris m", "Geschrei"],
["cliens", "-entis", "Abhängiger"],
["coepi", "ich habe begonnen"],
["cogere", "coegi, coactum", "1. versammeln\n2. zwingen"],
["cognoscere", "-gnovi, -gnitum", "1. erkennen\n2. erfahren"],
["cohors", "-rtis f", "Kohorte"],
["cohortari", "-tus sum", "1. auffordern\n2. Mut aussprechen"],
["collis", "-is m", "Hügel"],
["collocare", "-vi, -tum", "aufstellen"],
["colloquium", "-ii n", "Unterredung"],
["commeatus", "-us m", "1. Nachschub\n2. Versorgungsgüter"],
["committere", "-misi, -missum", "1. zulassen\n2. anvertrauen", [
    ["proelium committere", "den Kampf beginnen"]]],
["commodus", "(-a, -um)", "bequem"],
["communis", "(-e), -is", "gemeinsam"],
["commutatio", "-onis f", "Veränderung"],
["comparare", "-vi, -tum", "vorbereiten, regeln"],
["complere", "-vi, -tum", "anfüllen"],
["complures", "(-ra) -ium", "mehrere"],
["comprehendere", "-hendi, -hensum", "ergreifen"],
["conari", "-tus sum", "versuchen"],
["concedere", "-cessi, -cessum", "1. erlauben\n2. geben"],
["concilium", "-ii n", "Versammlung"],

# ================ SEITE 6/7 ================ #

["concurrere", "-curri, -cursum", "1. laufen\n2. zusammenlaufen"],
["condicio", "-onis f", "Bedingung"],
["conferre", "-fero, -tuli, collatum", "zusammentragen", [
    ["se conferre", "sich begeben"]]],
["conficere", "-io, -feci, -fectum", "beenden", [
    ["confectus", "erschöpft"]]],
["confidere", "-fisus sum", "vertrauen"],
["confimare", "-vi, -tum", "1. versichern\n2. verstärken\n3. ermutigen",],
["conicere", "-io, -ieci, -iectum", "werfen"],
["coniungere", "-iunxi, -iuntum", "verbinden"],
["coniurare", "-vi, -tum", "sich verschwören"],
["consequi", "-secutus sum", "1. verfolgen\n2. erreichen"],
["considere", "-sedi, -sessum", "sich niederlassen"],
["consilium", "-ii n", "1. Rat\n2. Plan\n3. Beschluß"],
["consistere", "-stiti", "haltmachen"],
["conspectus", "-us m", "1. Anblick\n2. Sichtweite"],
["conspicere", "-io, -spexi, -spectum", "erblicken"],
["constat", "es steht fest"],
["constituere", "-tui, -tutum", "1. aufstellen\n2. beschließen"],
["consuevi", "ich bin gewohnt"],
["consuetudo", "-dinis f", "Gewohnheit"],
["consulere", "-lui, -ltum", "1. (m. Akk.) beraten\n2. (m. Dat.) sich kümmern um"],
["consumere", "-sumpsi, -sumptum", "verbrauchen"],
["contendere", "-tendi, -tentum", "1. eilen\n2. kämpfen"],

["continens", "-entis (f)", "1. ununterbrochen\n2. Festland"],
["continere", "-ui, -tentum", "halten, festhalten", [
    ["se continere", "sich aufhalten"]]],
["contra", "1. gegen\n2. dagegen"],
["controversia", "-ae f", "Streit"],
["convenire", "-veni, -ventum", "zusammenkommen"],
["convertere", "-verti, -versum", "wenden"],
["convocare", "-vi, -tum", "zusammenrufen"],
["copia", "-ae f", "1. Menge\n2. Plural: Truppen"],
["cornu", "-us n", "Flügel (des Heeres)"],
["corpus", "-poris n", "Körper"],
["cottidie", "täglich"],
["creber", "(-bra, -brum)", "zahlreich"],
["credere", "-didi, -ditum", "glauben"],
["cum (Konjunktion)", "I. (mit Ind.): als/wenn\nII. (mit Konj.) als/da/obgleich", 
    [["cum ... tum", "sowohl ... als auch besonders"]]],
["cum (Präposition)", "mit"],
["cupidus", "(-a, -um)", "begierig"],
["curare", "-vi, -tum", "(für etw.) sorgen"],
["cursus", "-us m", "Lauf"],
["custodia", "-ae f", "Wache"],
# -------- D -------- #
["dare", "do, dedi, datum", "geben"],
["de", "1. von (... herab)\n2. über\n3. in Beziehung auf"],

["debere", "-ui, -itum", "müssen", [
    ["non debere", "nicht müssen, nicht brauchen"]]],
["decem", "zehn"],
["decimus", "(-a, -um)", "der zehnte"],
["dedere", "-didi, -ditum", "ausliefern", [
    ["se dedere", "sich ergeben"]]],
["deditio", "-onis f", "Kapitulation"],
["deducere", "-duxi, -ductum", "1. wegführen\n2. bringen"],
["deesse", "-sum, -fui", "fehlen"],
["defectio", "-onis f", "Aufstand"],
["defendere", "-fendi, -fensum", "verteidigen"],
["deferre", "-fero, -tuli, -latum", "1. hinbringen\n2. melden"],
["deficere", "-io, -feci, -fectum", "1. abfallen\n2. ausgehen"],
["deicere", "-io, -ieci, -iectum", "herabwerfen"],
["deligere", "-legi, -lectum", "auswählen"],
["demonstare", "-vi, -tum", "darlegen"],
["desistere", "-stiti", "aufhören"],
["desperare", "-vi, -tum", "die Hoffnung aufgeben"],
["dexter", "(-tra, -trum)", "der rechte"],
["dicere", "dixi, dictum", "sagen"],
["dies", "-ei m/f", "1. Tag (m)\n2. Termin (f)"],
["difficultas", "-atis f", "Schwierigkeit"],
["dignitas", "-atis f", "Würde"],
["diligentia", "-ae f", "Sorgfalt"],
["dimicare", "-vi, -tum", "kämpfen"],
["dimittere", "-misi, -missum", "wegschicken"],
["diripere", "-io, -ui, -reptum", "plündern"],
["discedere", "-cessi, -cessum", "weggehen"],
["disponere", "-posui, -positum", "aufstellen"],

["diu", "Komp. diutius", "lange"],
["dividere", "-visi", "-visum", "1. trennen\n2. teilen"],
["docere", "-ui, -tum", "darlegen"],
["dolor", "-oris m", "Schmerz"],
["domus", "-us f", "Haus"],
["dubitare", "-vi, -tum", "1. zweifeln\n2. zögern"],
["ducere", "duxi, ductum", "1. führen\n2. meinen, (für etw.) halten"],
["dum", "1. (mit Ind.) während\n2. (mit Konj.) bis"],
["duo", "(-ae, -o)", "zwei"],
["duodecim", "zwölf"],
["dux", "ducis m", "Führer"],
# -------- E -------- #
["educere", "-duxi, -ductum", "herausführen"],
["efficere", "-io, -feci, -fectum", "bewirken, erreichen"],
["egredi", "-ior, -gressus sum", "hinausgehen"],
["enim", "nämlich"],
["eo", "1. dorthin\n2. (mit Komp.) desto"],
["eques", "equitis m", "Reiter", "[equester (-tris, -tre), -tris]", [
    ["proelium equestre", "Reitergefecht"]]],
["equitatus", "-us m", "Reiterei"],
["equus", "-i m", "Pferd"],
["eruptio", "-onis f", "Ausbruch"],
["esse", "sum, fui", "sein"],
["et", "und", [
    ["et ... et", "sowohl"]]],
["etiam", "1. auch\n2. (mit Komp.) noch\n3. sogar"],
["etsi", "obgleich"],
["evocare", "-vi, -tum", "1. herausrufen\n2. kommen lassen"],

# ================ SEITE 8/9 ================ #

["e, ex", "1. aus\n2. auf Grund\n3. seit"],
["excedere", "-cessi, -cessum", "sich entfernen"],
["excipere", "-io, -cepi, -ceptum", "aufnehmen"],
["exercere", "-ui, -itum", "üben"],
["exercitus", "-us m", "Heer"],
["exire", "-eo, -ii, -itum", "hinausgehen"],
["existimare", "-vi, -tum", "glauben"],
["expeditus", "(-a, -um)", "1. unbehindert\n2. einsatzbereit"],
["expellere", "-puli, -pulsum", "vertreiben"],
["explorare", "-vi, -tum", "auskundschaften", [
    ["victoria explorata", "sicherer Sieg"]]],
["explorator", "-oris m", "Kundschafter"],
["expugnare", "-vi, -tum", "erobern"],
["exspectare", "-vi, -tum", "1. abwarten\n2. erwarten"],
["extremus", "(-a, um)", "der äußerste, der letzte"],
# -------- F -------- #
["facere", "-io, feci, factum", "1. tun, handeln\n2. machen", [
    ["fieri", "geschehen"]]],
["facile", "leicht"],
["facultas", "-atis f", "Möglichkeit"],
["fama", "-ae f", "Gerücht"],
["fere", "1. fast\n2. etwa\n3. im allgemeinen"],
["ferre", "fero, tuli, latum", "1. tragen, bringen\n2. ertragen"],
["fides", "-ei f", "1. Treue\n2. Vertrauen\n3. Zuverlässigkeit\n4. Schutz"],

["filius", "-ii m", "Sohn"],
["finis", "-is m", "1. Ende\n2. Plural: Gebiet"],
["finitimus", "(-a, -um)", "1. benachbart\n2. Nachbar"],
["firmus", "(-a, -um)", "stark"],
["flumen", "-minis n", "Fluß"],
["fortis", "(-e), -is", "tapfer"],
["fortuna", "-ae f", "1. Schicksal\n2. Glück\n3. Plural: Besitz"],
["fossa", "-ae f", "Graben"],
["frater", "-tris m", "Bruder"],
["frumentarius", "(-a, -um)", "das Getreide betreffend", [
    ["res frumentaria", "Proviant"]]],
["frumentum", "-i n", "Getreide"],
["fuga", "-ae f", "Flucht"],
["fugere", "-io, fugi, fugitum", "fliehen"],
# -------- G -------- #
["genus", "-neris n", "Art", "[gerere, gessi, gestum]", [
    ["geri (pass.)", "geschehen"],
    ["bellum gerere", "Krieg führen"]]],
["gratia", "-ae f", "1. Ansehen\n2. Dank"],
["gravis", "(-e), -is", "1. schwer\n2. ernst"],
# -------- H -------- #
["habere", "-ui, -itum", "haben"],
["hiberna", "-orum n", "Winterlager"],
["hic", "(haec, hoc)", "dieser"],
["hiemare", "-vi, -tum", "überwintern"],
["hiems", "-mis f", "Winter"],
["homo", "-minis m", "Mensch"],
["hora", "-ae f", "Stunde"],
["hortari", "-tus sum", "auffordern"],
["hostis", "-is m", "Feind"],
["huc", "hierher"],
# -------- I -------- #
["iam", "1. schon\n2. (neg.) mehr (z.B. neque iam)"],
["ibi", "dort"],
["idem", "(eadem, idem)", "derselbe"],
["idoneus", "(-a, -um)", "geeignet"],
["ignis", "-is m", "Feuer"],
["ille", "(illa, illud)", "jener"],
["impedimenta", "Gepäck"],
["impedire", "-vi, -tum", "behindern"],
["imperare", "-vi, -tum", "1. befehlen\n2. anfordern"],
["imperator", "-oris m", "Feldherr"],
["imperitus", "(-a, -um)", "unerfahren"],
["imperium", "-ii n", "1. Oberbefehl\n2. Herrschaft"],
["impetrare", "durchsetzen"],
["impetus", "-us m", "Angriff"],
["in", "I.(m. Akk.) in/nach/gegen\nII.(m. Abl.) in/auf/bei"],
["incendere", "-cendi, -censum", "anzünden"],
["incitare", "-vi, -tum", "antreiben"],
["incolere", "-colui, -cultum", "1. wohnen\n2. bewohnen"],
["incolumnis", "(-e), -is", "wohlbehalten, ohne Verluste"],
["incommodum", "-i n", "Unannehmlichkeit"],
["inde", "1. von dort\n2. daraufhin"],
["inferior", "(-ius), -oris Superl. infimus", "der untere"],

["inferre", "infero, intuli, illatum", "1. bringen\n2. zufügen", [
    ["bellum inferre", "den Krieg beginnen"],
    ["singa inferre", "angreifen"]]],
["iniquus", "(-a, um)", "1. uneben\n2. ungleich\n3. ungünstig\n4. ungerecht"],
["inire", "-eo, -ii, -itum", "beginnen", [
    ["consilium inire", "einen Plan fassen"]]],
["initium", "-ii n", "Anfang"],
["iniuria", "-ae f", "Unrecht, Ungerechtigkeit"],
["inopia", "-ae f", "Mangel"],
["inquit", "sagt(e) er"],
["insequi", "-secutus sum", "1. folgen\n2. verfolgen"],
["instituere", "-tui, -tutum", "1. einrichten\n2. anfangen"],
["intruere", "-struxi, -structum", "aufstellen"],
["insula", "-ae f", "Insel"],
["intellegere", "-lexi, -lectum", "merken"],
["inter", "zwischen, unter"],
["intercludere", "-clusi, -clusum", "abschneiden"],
["interficere", "-io, -feci, -fectum", "töten"],
["interim", "inzwischen"],
["intermittere", "-misi, -missum", "1. unterbrechen\n2. dazwischentreten lassen(Zeit, Raum)"],
["intra", "innerhalb"],
["ipse", "(ipsa, ipsum)", "1. selbst persönlich\n2. selbst gerade\n3. selbst schon"],
["ire", "eo, ii, itum", "gehen"],
["is", "(ea, id)", "1. dieser\n2. der (z.B. is, qui)\n3. er"],
["ita", "so"],
["itaque", "daher"],
["item", "ebenso"],

# ================ SEITE 10/11 ================ #

["iter", "itineris n", "1. Weg\n2. Marsch"],
["iubere", "iussi, iussum", "befehlen"],
["iudicare", "-vi, -tum", "1. entscheiden\n2. meinen"],
["iugum", "-i n", "Bergrücken"],
["ius", "iuris n", "Recht"],
["ius iurandum", "-i n" "Eid"],
# -------- L -------- #
["labor", "-oris m", "1. Tätigkeit, Anstrengung\n2. Mühe"],
["laborare", "-vi, -tum", "in Schwierigkeiten sein"],
["latus", "(-a, -um)", "breit", [
    ["late", "weit"]]],
["latus", "-teris n", "Seite"],
["laus", "laudis f", "Ruhm"],
["legatio", "-onis f", "Gesandschaft"],
["legatus", "-i m", "1. Gesandter\n2. Unterfeldherr, Legat"],
["legio", "-onis f", "Legion"],
["levis", "(-e), -is", "leicht"],
["lex", "legis f", "Gesetz"],
["liberi", "-orum m", "Kinder"],
["libertas", "-atis f", "Freiheit"],
["licet", "-uit", "es ist erlaubt"],
["litterae", "-arum f", "Brief"],
["locus", "-i m", "1. Ort\n2. Stellung"],
["longe", "1. weit\n2. bei weitem(z. B. maximus)"],
["longus", "(-a, -um)", "lang"],
["lux", "lucis f", "Licht"],
# -------- M -------- #
["magis", "Superl. maxime", "mehr"],
["magistratus", "-us m", "1. Beamter\n2. Amt"],

["magnitudo", "-dinis f", "Größe"],
["magnus", "(-a, -um)", "groß", "Komp. maior Superl. maximus"],
["mandare", "-vi, -tum", "auftragen"],
["manus", "-us f", "1. Hand\n2. Schar"],
["mare", "maris n", "Meer"],
["maturus", "(-a, -um)", "reif"],
["medius", "(-a, -um)", "1. der mittlere\n2. mitten (z.B. per medios fines)"],
["memoria", "-ae f", "1. Erinnerung\n2. Zeit"],
["merere", "-ui", "verdienen"],
["miles", "-litis m", "Soldat"],
["militaris", "(-e), -is", "militärisch"],
["mille", "Plur. milia", "tausend"],
["minuere", "-ui, -minutum", "vermindern"],
["minus", "Superl. minime", "weniger"],
["mittere", "misi, missum", "schicken"],
["modo", "nur"],
["modus", "-i m", "Art"],
["mons", "montis m", "Berg"],
["morari", "-tus sum", "1. sich aufhalten\n2. aufhalten"],
["mors", "mortis f", "Tod"],
["mos", "moris m", "Sitte"],
["motus", "-us m", "1. Bewegung\n2. Aufstand"],
["movere", "movi, motum", "bewegen", [
    ["castra movere", "aufbrechen"]]],
["multi", "(-ae, -a)", "viele"],
["munire", "-vi, -tum", "1. befestigen\n2. schützen\n3. befestigt anlegen(z.B. castra)"],

["munitio", "-onis f", "Befestigung"],
["murus", "-i m", "Mauer"],
# -------- N -------- #
["nam", "denn"],
["nanisci", "na(n)ctus sum", "zufällig finden, erlangen"],
["nasci", "natus sum", "entstehen", [
    ["natus", "geboren, stammend"]]],
["natio", "-onis f", "Volk"],
["natura", "-ae f", "Beschaffenheit"],
["navis", "-is f", "Schiff"],
["ne", "daß nicht, damit nicht"],
["ne ... quidem", "nicht einmal"],
["necessarius", "(-a, -um)", "notwendig", "Adv. necessario"],
["negat + Akk.(hinzugefügt)", "er sagt, dass er nicht...", ],
["neglegere", "-lexi, -lectum", "nicht beachten"],
["negotium", "-ii n", "Aufgabe, Sache"],
["nemo", "niemand"],
["neque, nec", "1. und nicht\n2. aver nicht\n3. auch nicht", [
    ["neque ... neque", "weder ... noch"]]],
["neve, neu", "und daß nicht, und damit nicht"],
["nihil", "1. nichts\n2. in keiner Weise"],
["nisi", "1. wenn nicht\n2. außer"],
["nobilis", "(-e), -is", "vornehm"],
["noctu", "bei Nacht"],
["nomen", "-minis n", "Name"],
["non", "nicht"],
["nonnulli", "(-ae, -a)", "einige"],
["nos", "wir"],
["noster", "(-tra, -trum)", "unser", [
    ["nostri", "unsere Leute"]]],
["novus", "(-a, -um)", "neu", [
    ["novissimus", "der letzte"]]],
["nox", "noctis f", "Nacht"],
["nullus", "(-a, -um)", "kein"],

["numerus", "-i m", "Zahl"],
["nuntiare", "-vi, -tum", "melden"],
["nuntius", "-ii m", "1. Bote\n2. Nachricht"],
# -------- O -------- #
["ob", "wegen"],
["obsidere", "-sedi, -sessum", "belagern"],
["obsides", "-um", "m", "Geiseln"],
["obtinere", "-ui, -tentum", "innehaben"],
["occidere", "-cidi, -cisum", "töten"],
["occultare", "-vi, -tum", "verbergen"],
["occupare", "-vi, -tum", "besetzen", [
    ["occupatus", "beschäftigt"]]],
["occurrere", "-curri, -cursum", "entgegenlaufen"],
["octo", "acht"],
["officium", "-ii n", "1. Pflicht\n2. Gehorsam"],
["omnino", "im ganzen, überhaupt"],
["omnis", "(-e), -is", "1. ganz\n2. jeder\n3. Plur. alle"],
["opinio", "-onis f", "1. Vermutung\n2. Ruf"],
["opportet", "-uit", "es ist nötig, man muß"],
["oppidum", "-i n", "Stadt"],
["opportunus", "(-a, -um)", "günstig"],
["oppugnare", "-vi, -tum", "angreifen"],
["oppugnatio", "-onis f", "Bestürmung"],
["opus", "operis n", "1. Arbeit\n2. Befestigung", [
    ["opus est", "es ist nötig"]]],
["oratio", "-onis f", "Rede"],
["ordo", "-dinis m", "1. Reihe\n2. Rang"],
["oriri", "ortus sum", "entstehen"],
["ostendere", "-tendi", "1. zeigen\n2. erklären"],
]
