vocabulary = [
# ================ SEITE 1 ================ #

# -------- A -------- #
["a, ab", "von, von ... her"],
["abdere", "-didi, -ditum", "verbergen"],
["abesse", "-sum, afui", "entfernt sein"],
["accedere", "-cessi, -cessum", "herankommen", [
    ["accedit", "es kommt hinzu"]]],
["accidere", "accidi", "geschehen"],
["accipere", "-io, -cepi, -ceptum", "empfangen"],
["acies", "-ei f", "1. Schlachtordnung\n2. Heeresgruppe(in der Schlacht)"],
["acriter", "heftig"],
["ad", "1. zu\n2. in der Nähe von"],
["adducere", "-duxi, -ductum", "1. hinführen\n2. veranlassen"],
["adesse", "-sum, -fui", "da sein"],
["adire", "-eo -ii, -itum", "hingehen"],
["aditus", "-us m", "Zugang"],
["administrare", "-vi, -tum", "durchführen"],
["adoriri", "-ortus sum {dep.}", "angreifen"],
["adulescens", "-entis m", "1. jung\n2. junger Mann"],
["adventus", "-us m", "Ankunft"],
["aedificium", "-ii n", "Gehöft {Bauernhof, Gebäude}"],
["aequus", "(-a, -um)", "1. eben\n2. gleich\n3. günstig\n4. gerecht"],
["aestus", "-us m", "Flut"],
["afferre", "affero, attuli, allatum", "bringen"],
["ager", "-gri m", "Feld"],
["agere", "egi, actum", "1. tun\n2. verhandeln"],
["agger", "-eris m", "Erdwall"],
["agmen", "-minis n", "Heer (auf dem Marsch)"],

["aliquis", "(aliquid) (subst.)", "irgendjemand, -einer, (-etwas)"],
["aliqui", "(-quae, -quod) (adj.)", "irgendein, (-eine)", "{'aliqui nomo'}"],
["alius", "(-a, -ud)", "ein anderer", [
    ["alii ... alii", "die einen ... die anderen"]]],
["alter", "-era -erum", "1. der andere\n2. der zweite", [
    ["alter ... alter", "der eine ... der andere"]]],
["altitudo", "-dinis f", "1. Höhe\n2. Tiefe"],
["altus", "(-a, -um)", "1. hoch\n2. tief"],
["amicitia", "-ae f", "Freundschaft"],
["amicus", "-i m", "Freund"],
["amittere", "-misi, -missum", "verlieren"],
["amplius", "mehr"],
["angstus", "(-a, -um)", "eng"],
["animadvertere", "-verti, -versum", "bemerken"],
["animus", "-i m", "Inneres: Geist, Herz, Mut"],
["annus", "-i m", "Jahr"],
["ante", "1. vor\n2. vorher"],
["apertus", "(-a, -um)", "1. offen\n2. ungeschützt"],
["appellare", "-vi, -tum", "1. ansprechen\n2. nennen"],
["appropinquare", "-vi", "sich nähern"],
["apud", "bei"],
["arbitrari", "-tus sum {dep.}", "meinen"],
["arcessere", "-sivi, -situm", "herbeirufen"],
["arma", "-orum n {pl.}", "Waffen"],
["armare", "-vi, -tum", "bewaffnen"],
["ascendere", "-scendi, -scensum", "hinaufsteigen"],
["at", "aber"],
["atque, ac", "1. und\n2. wie, als (z.B. alius atque)"],

["attingere", "attigi, attactum", "berühren"],
["attribuere", "-ui -utum", "zuteilen"],
["auctoritas", "-atis f", "Ansehen"],
["audere", "ausus sum", "wagen"],
["audire", "-vi -tum", "hören"],
["augere", "auxi, auctum", "vergrößern"],
["aut", "oder", [
    ["aut ... aut", "entweder ... oder"]]],
["autem", "aber"],
["auxilium", "-ii n", "Sg: Hilfe\nPl: Hilfstruppen"],
# -------- B -------- #
["barbarus", "(-a, -um)", "1. unkultiviert\n2. der Fremde(= Nichtrömer)"],
["bellum", "-i n", "Krieg"],
["beneficium", "-ii n", "1. Wohltat\n2. das Verdienst"],
["bonus", "(-a, -um)", "gut", "Komp. melior\nSuperl. optimus"],
# -------- C -------- #
["caedes", "-is f", "Morden"],
["calamitas", "-atis f", "Niederlage"],
["capere", "-io, cepi, captum", "1. fassen\n2. fangen\n3. einnehmen"],
["captivus", "-i m", "Gefangener"],
["castellum", "-i n", "Befestigung"],
["castra", "-orum n", "Lager"],
["casus", "-us m", "Ereignis, Situation", [
    ["casu", "durch Zufall"]]],
["caus[a]", "-ae f", "1. Sache\n2. Ursache, Grund"],
["caus[ā]", "wegen"],
["cedere", "cessi, cessum", "zurückweichen"],
["celeritas", "-atis f", "Schnelligkeit"],

["celeriter", "schnell"],
["centrum", "hundert"],
["centurio", "-onis m", "Hauptmann, Centurio"],
["certus", "(-a, -um)", "bestimmt", [
    ["certiorem facere", "benachrichtigen"]]],
["circiter", "ungefähr"],
["circumvenire", "-veni, -ventum", "umzingeln"],
["civitas", "-atis f", "Staat, Volk"],
["clamor", "-oris m", "Geschrei"],
["cliens", "-entis", "Abhängiger"],
["coepi", "ich habe begonnen"],
["cogere", "coegi, coactum", "1. versammeln\n2. zwingen"],
["cognoscere", "-gnovi, -gnitum", "1. erkennen\n2. erfahren"],
["cohors", "-rtis f", "Kohorte"],
["cohortari", "-tus sum", "1. auffordern\n2. Mut aussprechen"],
["collis", "-is m", "Hügel"],
["collocare", "-vi, -tum", "aufstellen"],
["colloquium", "-ii n", "Unterredung"],
["commeatus", "-us m", "1. Nachschub\n2. Versorgungsgüter"],
["committere", "-misi, -missum", "1. zulassen\n2. anvertrauen", [
    ["proelium committere", "den Kampf beginnen"]]],
["commodus", "(-a, -um)", "bequem"],
["communis", "(-e), -is", "gemeinsam"],
["commutatio", "-onis f", "Veränderung"],
["comparare", "-vi, -tum", "vorbereiten, regeln"],
["complere", "-vi, -tum", "anfüllen"],
["complures", "(-ra) -ium", "mehrere"],
["comprehendere", "-hendi, -hensum", "ergreifen"],
["conari", "-tus sum", "versuchen"],
["concedere", "-cessi, -cessum", "1. erlauben\n2. geben"],
["concilium", "-ii n", "Versammlung"],

# ================ SEITE 2 ================ #

["concurrere", "-curri, -cursum", "1. laufen\n2. zusammenlaufen"],
["condicio", "-onis f", "Bedingung"],
["conferre", "-fero, -tuli, collatum", "zusammentragen", [
    ["se conferre", "sich begeben"]]],
["conficere", "-io, -feci, -fectum", "beenden", [
    ["confectus", "erschöpft"]]],
["confidere", "-fisus sum", "vertrauen"],
["confimare", "-vi, -tum", "1. versichern\n2. verstärken\n3. ermutigen",],
["conicere", "-io, -ieci, -iectum", "werfen"],
["coniungere", "-iunxi, -iuntum", "verbinden"],
["coniurare", "-vi, -tum", "sich verwschwören"],
["consequi", "-secutus sum", "1. verfolgen\n2. erreichen"],
["considere", "-sedi, -sessum", "sich niederlassen"],
["consilium", "-ii n", "1. Rat\n2. Plan\n3. Beschluß"],
["consistere", "-stiti", "haltmachen"],
["conspectus", "-us m", "1. Anblick\n2. Sichtweite"],
["conspicere", "-io, -spexi, -spectum", "erblicken"],
["constat", "es steht fest"],
["constituere", "-tui, -tutum", "1. aufstellen\n2. beschließen"],
["consuevi", "ich bin gewohnt"],
["consuetudo", "-dinis f", "Gewohnheit"],
["consulere", "-lui, -ltum", "1. (m. Akk.) beraten\n2. (m. Dat.) sich kümmern um"],
["consumere", "-sumpsi, -sumptum", "verbrauchen"],
["contendere", "-tendi, -tentum", "1. eilen\n2. kämpfen"],

["continens", "-entis (f)", "1. ununterbrochen\n2. Festland"],
["continere", "-ui, -tentum", "halten, festhalten", [
    ["se continere", "sich aufhalten"]]],
["contra", "1. gegen\n2. dagegen"],
["controversia", "-ae f", "Streit"],
["convenire", "-veni, -ventum", "zusammenkommen"],
["convertere", "-verti, -versum", "wenden"],
["convocare", "-vi, -tum", "zusammenrufen"],
["copia", "-ae f", "1. Menge\n2. Plural: Truppen"],
["cornu", "-us n", "Flügel (des Heeres)"],
["corpus", "-poris n", "Körper"],
["cottidie", "täglich"],
["creber", "(-bra, -brum)", "zahlreich"],
["credere", "-didi, -ditum", "glauben"],
["cum (Konjunktion)", "I. (mit Ind.): als/wenn\nII. (mit Konj.) als/da/obgleich", 
    [["cum ... tum", "sowohl ... als auch besonders"]]],
["cum (Präposition)", "mit"],
["cupidus", "(-a, -um)", "begierig"],
["curare", "-vi, -tum", "(für etw.) sorgen"],
["cursus", "-us m", "Lauf"],
["custodia", "-ae f", "Wache"],
# -------- D -------- #
["dare", "do, dedi, datum", "geben"],
["de", "1. von (... herab)\n2. über\n3. in Beziehung auf"],

["debere", "-ui, -itum", "müssen", [
    ["non debere", "nicht müssen, nicht brauchen"]]],
["decem", "zehn"],
["decimus", "(-a, -um)", "der zehnte"],
["dedere", "-didi, -ditum", "ausliefern", [
    ["se dedere", "sich ergeben"]]],
["deditio", "-onis f", "Kapitulation"],
["deducere", "-duxi, -ductum", "1. wegführen\n2. bringen"],
["deesse", "-sum, -fui", "fehlen"],
["defectio", "-onis f", "Aufstand"],
["defendere", "-fendi, -fensum", "verteidigen"],
["deferre", "-fero, -tuli, -latum", "1. hinbringen\n2. melden"],
["deficere", "-io, -feci, -fectum", "1. abfallen\n2. ausgehen"],
["deicere", "-io, -ieci, -iectum", "herabwerfen"],
["deligere", "-legi, -lectum", "auswählen"],
["demonstare", "-vi, -tum", "darlegen"],
["desistere", "-stiti", "aufhören"],
["desperare", "-vi, -tum", "die Hoffnung aufgeben"],
["dexter", "(-tra, -trum)", "der rechte"],
["dicere", "dixi, dictum", "sagen"],
["dies", "-ei m/f", "1. Tag (m)\n2. Termin (f)"],
["difficultas", "-atis f", "Schwierigkeit"],
["dignitas", "-atis f", "Würde"],
["diligentia", "-ae f", "Sorgfalt"],
["dimicare", "-vi, -tum", "kämpfen"],
["dimittere", "-misi, -missum", "wegschicken"],
["diripere", "-io, -ui, -reptum", "plündern"],
["discedere", "-cessi, -cessum", "weggehen"],
["disponere", "-posui, -positum", "aufstellen"],

["diu", "Komp. diutius", "lange"],
["dividere", "-visi", "-visum", "1. trennen\n2. teilen"],
["docere", "-ui, -tum", "darlegen"],
["dolor", "-oris m", "Schmerz"],
["domus", "-us f", "Haus"],
["dubitare", "-vi, -tum", "1. zweifeln\n2. zögern"],
["ducere", "duxi, ductum", "1. führen\n2. meinen, (für etw.) halten"],
["dum", "1. (mit Ind.) während\n2. (mit Konj.) bis"],
["duo", "(-ae, -o)", "zwei"],
["duodecim", "zwölf"],
["dux", "ducis m", "Führer"],
# -------- E -------- #
["educere", "-duxi, -ductum", "herausführen"],
["efficere", "-io, -feci, -fectum", "bewirken, erreichen"],
["egredi", "-ior, -gressus sum", "hinausgehen"],
["enim", "nämlich"],
["eo", "1. dorthin\n2. (mit Komp.) desto"],
["eques", "equitis m", "Reiter", "[equester (-tris, -tre), -tris]", [
    ["proelium equestre", "Reitergefecht"]]],
["equitatus", "-us m", "Reiterei"],
["equus", "-i m", "Pferd"],
["eruptio", "-onis f", "Ausbruch"],
["esse", "sum, fui", "sein"],
["et", "und", [
    ["et ... et", "sowohl"]]],
["etiam", "1. auch\n2. (mit Komp.) noch\n3. sogar"],
["etsi", "obgleich"],
["evocare", "-vi, -tum", "1. herausrufen\n2. kommen lassen"],

# ================ SEITE 3 ================ #

["e, ex", "1. aus\n2. auf Grund\n3. seit"],
["excedere", "-cessi, -cessum", "sich entfernen"],
["excipere", "-io, -cepi, -ceptum", "aufnehmen"],
["exercere", "-ui, -itum", "üben"],
["exercitus", "-us m", "Heer"],
["exire", "-eo, -ii, -itum", "hinausgehen"],
["existimare", "-vi, -tum", "glauben"],
["expeditus", "(-a, -um)", "1. unbehindert\n2. einsatzbereit"],
["expellere", "-puli, -pulsum", "vertreiben"],
["explorare", "-vi, -tum", "auskundschaften", [
    ["victoria explorata", "sicherer Sieg"]]],
["explorator", "-oris m", "Kundschafter"],
["expugnare", "-vi, -tum", "erobern"],
["exspectare", "-vi, -tum", "1. abwarten\n2. erwarten"],
["extremus", "(-a, um)", "der äußerste, der letzte"],
# -------- F -------- #
["facere", "-io, feci, factum", "1. tun, handeln\n2. machen", [
    ["fieri", "geschehen"]]],
["facile", "leicht"],
["facultas", "-atis f", "Möglichkeit"],
["fama", "-ae f", "Gerücht"],
["fere", "1. fast\n2. etwa\n3. im allgemeinen"],
["ferre", "fero, tuli, latum", "1. tragen, bringen\n2. ertragen"],
["fides", "-ei f", "1. Treue\n2. Vertrauen\n3. Zuverlässigkeit\n4. Schutz"],

["filius", "-ii m", "Sohn"],
["finis", "-is m", "1. Ende\n2. Plural: Gebiet"],
["finitimus", "(-a, -um)", "1. benachbart\n2. Nachbar"],
["firmus", "(-a, -um)", "stark"],
["flumen", "-minis n", "Fluß"],
["fortis", "(-e), -is", "tapfer"],
["fortuna", "-ae f", "1. Schicksal\n2. Glück\n3. Plural: Besitz"],
["fossa", "-ae f", "Graben"],
["frater", "-tris m", "Bruder"],
["frumentarius", "(-a, -um)", "das Getreide betreffend", [
    ["res frumentaria", "Proviant"]]],
["frumentum", "-i n", "Getreide"],
["fuga", "-ae f", "Flucht"],
["fugere", "-io, fugi, fugitum", "fliehen"],
# -------- G -------- #
# ...

]